### ISSUE TITLE
Auto Backup

### ISSUE THREAD

**Issue by haappi** [duckNation/SMPCore#20]
See what region files a player walks into(or use bitwise with chunk coords), POST it to my api or something and save it every 4 hours

Also save surrounding region files? (1-2) in each direction??

Automatically use zst on max compression (while trying not to max out cpu)

# Directory
. ---
  /world
  /world_nether
  /world_the_end

Directory name should be Unix time stamp + human

**Comment by Joshy3282** [comment]
status?

**Comment by Joshy3282** [comment]
Hello is there a status on this

**Comment by haappi** [comment]
It's live, the script works as intended and makes partial backups every 3 hours. Full backups of loaded chunks are performed every 48 hours.
